[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "spenpal2000", email = "sanjeev.penupala@gmail.com"},
]
dependencies = [
    "networkx>=2.8.8",
    "matplotlib>=3.6.2",
    "ipykernel>=6.19.4",
]
requires-python = ">=3.10"
license = {text = "None"}
